update:
  nf-core/modules:
    cnvkit/batch: false
    picard/markduplicates: false
    unicycler: false
    minimap2/align: false
    samtools/faidx: false

lint:
  files_unchanged:
  - .gitignore
repository_type: pipeline
